### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.util.Collection org.bukkit.Location.getNearbyPlayers(double)'

### ISSUE THREAD

**Issue by Pengu1ns** [ruCakeMC/framedImage#8]
On 1.20.4, the plugin works fine until it tries to display an image. The logs just get spammed with the same error every time.

```
java.lang.NoSuchMethodError: 'java.util.Collection org.bukkit.Location.getNearbyPlayers(double)'
	at com.jnngl.framedimage.FramedImage.displayNextFrame(FramedImage.java:163) ~[?:?]
	at com.jnngl.framedimage.FramedImage.lambda$add$18(FramedImage.java:285) ~[?:?]
```

**Comment by AVuTuVA** [comment]
This plugin supports Paper (and Paper-compatible forks) only.
